---
title: Spring 2025 Course Schedule
repo-actions: false
page-layout: full
---

| Week | Date   | Guiding question   | Topic     | Story    | Case Study    | Assignment    |
|---|---|-----------|-----------|-----------|-----------|---|
|  1  | 1/28  | What is program evaluation? Where are we headed in this course? | [Introduction and Overview](lecture1.qmd) | [John Snow](/stories/john-snow-and-evidence-based-analysis.qmd) |                                        |               |
|  2  | 2/4 | Why do evaluation?      | [Goals and Types of Evaluation](lecture2.qmd)  | [High Line Park](/stories/high-line-park.qmd)    |  Jobs Plus in NYC | CR1  |
|  3  | 2/11 | How to identify causal effects?        | [Logic and Causal Models](lecture3.qmd)  | [Bombing in Vetnam -- War and Development](/stories/bombing-in-vietnam-war-and-development.qmd)     | Northwest Housing Alternatives | CR2 |
|  4  | 2/18 | Class following Monday schedule - No session |  | |  |   |        
|  5  | 2/25 | How do I account for everyone involved? | [Stakeholder Engagement](lecture4.qmd)  | [John Muir and National Park System](/stories/john-muir-and-national-park.qmd)     | ARPA-E |  CR3 |
|  6  | 3/4 | How do I use the scientific method in the real world?   | [Evaluation Designs: Randomized Experiences](lecture5.qmd)  | [Esther Duflo and RCTs](/stories/esther-duflo-and-rcts.qmd)     | Microfinance and RCT  | CR4 |
|  7  | 3/11 | What if a randomized experiment is not viable?   | Evaluation Designs: Quasi-experiments  |  Michael Greenstone and Air Quality    | Heating and Life-expectancy  | CR5  |
|  8  | 3/18 | How to do case study evaluation?   | Evaluation Designs: Qualitative methods  |   |  |   |
|  9  | 3/25 | How to manage challenges in evaluation?   | Overcome Resistance and Improve Organization Capacity  |  |  |  |
|  10  | 4/1 | Where does the data come from?   | Data Collection: Procedures, instrumentation, practical consideration  | Fei-fei Li and ImageNet   |  |  |
|  11  | 4/8 |  What methods make data tell accurate stories and solve problems?  | Data Analysis: Quantitative, qualitative, and mixed analysis  | Hans Rosling and Storytelling  |  | Proposal |
|  12  | 4/15 | No session-Spring Recess   |   |   |  |  |
|  13  | 4/22 | Is the program worthwhile? What happens next?   | Economic Evaluation and Performance Measurement  | Robert Bullard and Environmental Justice  | CBA of EPA Clean Air Act | CR |
|  14  | 4/29 | How to be an ethical evaluator?   | Ethics, Principles, and Standards  | The Moral Machine  |  |  |
|  15  | 5/6 | Presentation   |   |   |  |  |
|  16  | 5/13 | Evaluation report   |   |   |  |  |

: {.striped .responsive}

Note: CR: Case Response

:::{.content-hidden}
:::
