---
title: Spring 2024 Course Schedule
repo-actions: false
page-layout: full
---

[Syllabus](syllabus.qmd)

| Week | Date   | Guiding question   | Topic     | Story    | Case Study    | Assignment    |
|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
|  1  | Mar 9  | What is program evaluation? Where are we headed in this course? | [Introduction and Overview](lecture1.qmd) | [John Snow](john-snow-and-evidence-based-analysis.qmd) |                                        |               |
|  2  | Mar 16 | Why do evaluation?      | [Goals and Types of Evaluation](lecture2.qmd)  | [High Line Park](high-line-park.qmd)     | Case 1: Northwest Housing Alternatives | Case Response 1 |
|  3  | Mar 23 | How to identify causal effects?        | [Logic and Causal Models](lecture3.qmd)  | [Bombing, Heating, and Causal Models](bombing-heating-and-causal-models.qmd)     | Case 2: Jobs Plus in NYC | Case Response 2 |
|  4  | April 6 | How to account for everyone involved?        | [Stakeholder Engagement](lecture4.qmd)  | [John Muir and National Park System](john-muir-and-national-park.qmd)     | Case 3: ARPA-E | Case Response 3 |
|  5  | April 13 | How do I use the scientific method in the real world?   | [Evaluation Designs](lecture5.qmd)  | [Esther Duflo and RCTs](esther-duflo-and-rcts.qmd)     |   | Proposal due |
|  6  | April 20 | Where does the data for program evaluation come from?   | [Data Collection](lecture6.qmd)  | [Fei-fei Li and ImageNet](feifei-li-imagenet-and-ai-revolution.qmd)     |   |  |
|  7  | April 27 | What methods make data tell accurate stories and solve problems?   | [Data Analysis](lecture7.qmd)  | [Hans Rosling and Storytelling](hans-rosling-data-visualization-and-storystelling.qmd)  | Case 4: NYC Gifted & Talented Program | Case Response 4 |
|  8  | May 4 | Is the program worthwhile? What happens next?   | [Economic Evaluation and Performance Measurement](lecture8.qmd)  | [Robert Bullard and Environmental Justice](robert-bullard-and-environmental-justice.qmd)  | Case 5: CBA of EPA Clean Air Act | Case Response 5 |
|  9  | May 11 | How to be an ethical evaluator?   | [Ethics, Principles, and Standards](lecture9.qmd)  | [The Moral Machine](the-moral-machine-and-ethics.qmd)  |  |  |
|  10  | May 18 | What we have learned in the class?   | Final presentation  |   |  | Presentation |
|  11  | May 25 | How to do a sensible evaluation at reasonable costs?   | [Student Projects](students.qmd)  |   |  | Evaluation Report |

:::{.content-hidden}
:::
