## Course Description

Climate change is one of the biggest challenges of our time. This course offers a comprehensive and interdisciplinary approach to understanding the science behind climate change, the complex technological and policy considerations, and the necessary pathways to transition towards a carbon-neutral future. Over the course of the semester, we will delve into the fundamental concepts of climate science and explore the latest research on climate change. We will also examine the various energy technologies available and the challenges of transitioning towards a sustainable energy system. In addition, we will explore the policy and economic considerations that underpin energy and climate policy, and the social and cultural dimensions of this complex issue. Ultimately, the goal of this class is to provide students with a broad understanding of the challenges and opportunities associated with the energy and climate crisis. We hope to empower the students with the knowledge and skills needed to make a positive impact on climate solutions.
