---
title: Hans Rosling, Data Visualization, and Storytelling
author: Gang He
date: April 27, 2024
format: 
  html: 
    theme: cosmo
    css: /styles.css
    toc: true
#   link-external-icon: true
    link-external-newwindow: true
  
  pdf: 
    documentclass: article
    #classoption: [landscape]
    lof: false
    lot: false
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded
    #fontfamily: xelatex
    colorlinks: true
draft: true
draft-mode: unlinked
---

## Hans Rosling

- Swedish physician, academic and public speaker. 
- 1948 - 2017


## Gapminder and data storytelling

- *Don't Panic - The Truth about Population* (2013)
- *Don't Panic: How to End Poverty in 15 Years* (2015)
- "The world is better than you think"
- Book: *Factfulness: Ten Reasons We're Wrong About the World – and Why Things Are Better Than You Think*

>I'm a very serious "possibilist". That's something I made up. It means someone who neither hopes without reason, nor fears without reason, someone who constantly resists the overdramatic worldview. As a possibilist, I see all this progress, and it fills me with conviction and hope that further progress is possible. This is not optimistic. It is having a clear and reasonable idea about how things are. It is having a worldview that is constructive and useful.

--Han Rosling


## Thoughts for evaluation

- Facts are powerful
- Data visulization   
- Storytelling and narratives


## Further readings

<https://www.gapminder.org/>

<!--Include social share buttons-->

{{< include /files/includes/_socialshare.qmd >}}