---
title: John Muir and National Park
author: Gang He
date: April 6, 2024
format: 
  html: 
    theme: cosmo
    css: /styles.css
    toc: true
#   link-external-icon: true
    link-external-newwindow: true
  
  pdf: 
    documentclass: article
    #classoption: [landscape]
    lof: false
    lot: false
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded
    #fontfamily: xelatex
    colorlinks: true
#draft: true
---

## Who is John Muir

- Naturalist, author, environmental philosopher (1838-1914)
- "John of the Mountains"

## Muir and national park

- "Father of the National Parks"

>Climb the mountains and get their good tidings, Nature's peace will flow into you as sunshine flows into trees. The winds will blow their own freshness into you and the storms their energy, while cares will drop off like autumn leaves. As age comes on, one source of enjoyment after another is closed, but nature's sources never fail.

-- [Our National Parks](https://vault.sierraclub.org/john_muir_exhibit/writings/our_national_parks/) , 1901, page 56.

## Stakeholders

- The president (Theodore Roosevelt)
- Public support via books, popular magazine article, and the Sierra Club

## Outcomes

- US Congress, 1890, establising the Yosemite National Park
- The start of National Park System


## Thoughts for evaluation

- Beyond prices: public space, history, recreation, education, and American treasure  
- Evaluation indicators: visitors, local economy, what else?


## Further readings

- Walls, Margaret. 2022. “Economics of the US National Park System: Values, Funding, and Resource Management Challenges.” Annual Review of Resource Economics 14 (Volume 14, 2022): 579–96. <https://doi.org/10.1146/annurev-resource-111920-021401>.


<!--Include social share buttons-->

{{< include /files/includes/_socialshare.qmd >}}