---
title: Michael Greenstone and Environmental Economics
author: Gang He
date: March 11, 2025
bibliography: ../readings.bib
format: 
  html: 
    theme: cosmo
    css: /styles.css
    toc: true
#   link-external-icon: true
    link-external-newwindow: true
  
  pdf: 
    documentclass: article
    #classoption: [landscape]
    lof: false
    lot: false
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded
    #fontfamily: xelatex
    colorlinks: true
#draft: true
---

## Michael Greenstone

- Professor in Economics at Univeristy of Chicago
- Director of the Energy Policy Institute at Chicago (EPIC)


## Effects of Air Pollution

- 1-percent reduction in TSPs results in a 0.35 percent decline in the infant mortality rate at the county level
- 2500 fewer infants died from 1980–1982 recession than would have in the absence of the TSPs reductions

- [@chayImpactAirPollution2003]


## Effects of Climate Change

- By the end of the century climate change will lead to increases of 3 percent in the age-adjusted mortality rate and 11 percent in annual residential energy consumption.

- [@deschenesClimateChangeMortality2011a]


## Thoughts for Evaluation

- Economic shock and natural experience
- Make use of regulatory and climate data
- Communication for policy change


## Links

- [Climate Impact Lab](https://impactlab.org/)

- [Air Quality Life Index](https://aqli.epic.uchicago.edu/the-index/)

## References

::: {#refs}
:::


<!--Include social share buttons-->

{{< include /files/includes/_socialshare.qmd >}}